--- # Bootstrap Webservers
- hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
  - debug:
      var: target_service
  - name: install httpd
    yum:
      name: "{{ target_service }}"
      state: latest
    notify:
      - restart httpd
  - name: create index.html file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "{{ ansible_hostname }}"
      path: /var/www/html/index.html
    notify:
      - restart httpd
    register: task_debug
  - debug:
      msg: "{{ task_debug }}"
  handlers:
  - name: start httpd
    service:
      name: httpd
      state: restarted
    listen: "restart httpd"
